Move directories from mongod to mongodb
canonical/charmed-mongodb-snap pull request #12
Opened 2023-03-08 17:56 UTC by jardon

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
bug fix

* **What is the current behavior?** (You can also link to an open issue here)
- The data directory is placed under `$SNAP_COMMON/var/lib/mongod` and is inconsistent with the deb packages.
- The log directory is placed under `$SNAP_COMMON/var/log/mongod` and is inconsistent with the deb packages.

* **What is the new behavior (if this is a feature change)?**
- The data directory is updated to use `$SNAP_COMMON/var/lib/mongodb`.
- The data directory is updated to use `$SNAP_COMMON/var/log/mongodb`

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Yes.  The charm will need to be updated.

* **Other information**:
Nope.

2023-03-08 22:02 UTC, taurus-forever approved these changes

2023-03-09 09:57 UTC, MiaAltieri requested changes

2023-03-09 09:57 UTC, MiaAltieri commented on snap/hooks/install
> +mkdir -p "${SNAP_COMMON}/var/log/mongodb/"
```suggestion
# data related to mongodb workload stored here
mkdir -p "${SNAP_COMMON}/var/lib/mongodb/"
# metadata related to mongod should be stored separately 
mkdir -p "${SNAP_COMMON}/var/lib/mongod/"
mkdir -p "${SNAP_COMMON}/var/log/mongod/"
```
We want both `"${SNAP_COMMON}/var/lib/mongodb/"``"${SNAP_COMMON}/var/lib/mongod/"`

[motivation here](https://github.com/canonical/mongodb-operator/pull/176#discussion_r1129784914)

2023-03-09 09:57 UTC, MiaAltieri commented on snap/hooks/install
> +sed -i "s:/var/lib/mongodb:$SNAP_COMMON/var/lib/mongodb:g" $MONGO_CONFIG_FILE
```suggestion
sed -i "s:/var/log/mongodb/mongod.log:$SNAP_COMMON/var/log/mongod/mongod.log:g" $MONGO_CONFIG_FILE
sed -i "s:/var/lib/mongodb:$SNAP_COMMON/var/lib/mongodb:g" $MONGO_CONFIG_FILE
```
I might be wrong about the second line

2023-03-30 15:15 UTC, jardon commented
This PR is superseded by https://github.com/canonical/charmed-mongodb-snap/pull/27

2023-03-30 15:15 UTC, closed without merging